### ISSUE TITLE
Quest place-block stage item bug

### ISSUE THREAD

**Issue by shootcraft** [Blackvein/Quests#381]
some blocks that consist durability such as chiseledsmoothbrick are not working
Here the whole yaml file
http://pastebin.com/XRv1u1Gd

Here the specific part that the problem was
http://pastebin.com/sBFETaXa

**Comment by FlyingPikachu** [comment]
Continued from #361 

I see that the Quest refuses to load with the data tag. The editor will need to be updated.

**Comment by shootcraft** [comment]
Thanks, I will be waiting

**Comment by FlyingPikachu** [comment]
@shootcraft http://ci.ac3-servers.eu/job/Quests/110/

Please note that this experimental and only supports durability for block-break at the moment (so it won't work for block-place yet). Report back with any issues.

**Comment by shootcraft** [comment]
thank you so much, It will help me a lot, it will be nicer if it works on place block because most of the quests that i setup used that place block module

**Comment by FlyingPikachu** [comment]
Fixed in ecdfc8b All block events should now be supported. Give the latest dev build a try and create a _new_ issue if you experience any problems. Thanks!

**Comment by shootcraft** [comment]
so will it work on place-block module ?

**Comment by FlyingPikachu** [comment]
@shootcraft Test it and find out.

**Comment by shootcraft** [comment]
Thanks a lot, it really work, I finally able to launch my server with this feature , apparently it seems to have small quests editor bug that causing quests editor to unable to function properly but it still not a big deal since I still can config inside yaml file
